-- Drop existing if necessary, or just run this
CREATE TABLE IF NOT EXISTS students (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  roll_number TEXT,
  usn TEXT UNIQUE,
  sem TEXT,
  dept TEXT,
  mobile TEXT,
  parents_no TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS engagement_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  attention_score FLOAT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS phone_detection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  detected BOOLEAN,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
